name: Medium Writeups

on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches:
      - main

# Actions project permission
permissions:
  contents: write

jobs:
  proxy_check:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Go
      run: actions/setup-go@v4
      with:
        go-version: '1.20'  # Specify the version of Go you want to use

    - name: Scraping Medium Writeups
      run: go run main.go | tee -a README.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add .github/workflows/actions.yml
        IST_DATE=$(TZ='Asia/Kolkata' date +'%a %b %d %H:%M:%S IST %Y')
        git commit -m "Updated List: $IST_DATE"
        git push